### ISSUE TITLE
Is coffee gettable multiple times?

### ISSUE THREAD

**Issue by Binney** [ashbc/SoftClicker2#5]
On my game coffee seems to be buyable multiple times, whereas on Jack M's it isn't?

**Comment by kirstenland** [comment]
It shouldn't be gettable multiple times.

 I can see one thing that could cause this issue but don't know if this is the issue you've had. I think if you buy coffee with an active LM, the coffee disappears when the LM does. I'll try fixing this.

**Comment by kirstenland** [comment]
Should be fixed now.
